name: Update Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to (major.minor.patch)'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: bump version to ${{ github.event.inputs.version }}'
          branch: 'version-bump' 